"""added document embedding model

Revision ID: 2088930d2e5d
Revises: 9b3c7f4d2a1e
Create Date: 2026-02-01 11:21:25.844270

"""
from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2088930d2e5d'
down_revision = '9b3c7f4d2a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('embedding', Vector(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_embeddings_document_chunk')
    )
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_embeddings_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_embeddings_document_type'), ['document_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_embeddings_document_type'))
        batch_op.drop_index(batch_op.f('ix_document_embeddings_document_id'))

    op.drop_table('document_embeddings')
    # ### end Alembic commands ###
